---
- hosts: apache
  become: yes
  tasks:
    - name: install apache
      apt:
        name: apache2
        state: present
    - name: "Apache configuration"
      template:
        src: "inventaire.conf.j2"
        dest: "/etc/apache2/sites-available/inventory.conf"
        owner: "vagrant"
        group: "vagrant"
  # register execution result for template creation 
      register: apache_conf
  
  # debug instruction to get apache_conf
    - debug: var=apache_conf 
    - name: "Restart apache service"
      service:
        name: apache2
        state: restarted
  # restart if necessary
      when: apache_conf.changed

    - name: "Start apache service"
      service:
        name: apache2
        state: started
        enabled: yes
     

    
