---
- name: "install python2"
  hosts: all
  gather_facts: no
  tasks:
    - name: "Python2 installation using apt"
      become: yes
      # Dot not forget -y here to avoid apt's questions
      raw: apt install -y python-minimal
      args: 
        creates: "/usr/bin/python"
