---
- name: "Generate html file for each host"
  hosts: all
  #connection: local
  gather_facts: yes
  tasks: 
    - name: "html file generation"
      template: 
        src: "machineIP.html.j2"
        dest: "{{playbook_dir}}/{{inventory_hostname}}.html"
      connection: local
