---
- name: "mariadb installation"
  become: yes
  apt:
    name: "mariadb-server"
    state: "installed"

- name: "start mariadb service"
  become: yes
  service: 
        name: mysql
        state: started
        enabled: yes

- name: "mariadb-server installation"
  become: yes
  apt: 
     name: mariadb-server,python-mysqldb
     state: installed
     
