---

- name: "mediawiki directory" 
  become: yes
  file: 
    path: "{{mediawiki_directory}}"
   # path: name={{item}} state=present
    owner: "vagrant"
    group: "vagrant"
    state: directory
  #  with_items:
  #       - wget https://releases.wikimedia.org/mediawiki/1.31/mediawiki-1.31.1.tar.gz

- name: "uncompress mediawiki archive"
  become: yes
  unarchive:
  # src: "{{mediawiki_archive_url}}"
    src: /home/vagrant/test/mediawiki-1.31.1.tar.gz
    dest: "{{mediawiki_directory}}"
    owner: "vagrant"
    group: "vagrant"
    remote_src: yes
 # remove mediawiki-29.0/ from path
#    extra_opts: 
 #      - --transform
 #      - s/^mediawiki-[0-9\.]*\///

- name: "mediawiki configuration"
  become: yes
  become_user: "vagrant"
#  args:
#    chdir: "{{mediawiki_maintenance_directory}}"
  command:
    php install.php --scriptpath /{{mediawiki_name}}
       --dbname mediawiki --lang fr
       --dbuser {{mediawiki_db_user}}
       --dbpass {{mediawiki_db_password}}
       --pass {{mediawiki_admin_password}}
       --dbserver {{mediawiki_db_host}}
       {{mediawiki_title}} {{mediawiki_admin_user}}
 # env:
#    LC_ALL: C
  args: 
    # If localSettings
    creates: "{{mediawiki_directory}}/LocalSettings.php"
    chdir: "{{mediawiki_maintenance_directory}}"
