---
- name: "mediawiki database"
  become: yes
  mysql_db:
    name: "{{mediawiki_db_name}}"
    state: present

- name: "mediawiki user+ privileges"
  become: yes
  mysql_user:
    name:      "{{mediawiki_db_user}}"
    password:  "{{mediawiki_db_password}}"
    priv:      "{{mediawiki_db_name}}.*:ALL"
    state:     present
  with_items: "{{groups.apache}}"
